---
title: "Abstract"
author: "Zachary M. Smith"
date: "December 26, 2017"
output: html_document
---

```{r echo=FALSE}
knitr::opts_chunk$set(eval=evaluate, cache=cache.me)
```

“Improve health and function of ten percent of stream miles above the 2008 baseline for the watershed” is a goal in the 2014 Chesapeake Bay Agreement. The Chesapeake Bay Program (CBP) selected the “Chessie BIBI,” a stream macroinvertebrate index of biotic integrity, as its biological indicator of stream health. It will use the index to evaluate and report progress improving stream communities across the Chesapeake watershed. A 2008 baseline for the Chessie BIBI still needs to be established. Two sampling periods, intended to represent a 2008 baseline (i.e., 2000-2008 and 2004-2008), are explored using the results from the family-level region and bioregion Chessie BIBIs. Six methods are proposed and assessed for summarizing Chessie BIBI ratings for the Chesapeake Bay basin, each with their own strenghts and weaknesses. Ultimately, the selected method must accurately represent stream conditions in the Chesapeake Bay basin and allow for a robust way of evaluating trends within the basin.