---
title: "Introduction"
author: "Zachary M. Smith"
date: "December 26, 2017"
output: html_document
---

```{r echo=FALSE}
knitr::opts_chunk$set(eval=evaluate, cache=cache.me)
```

The Chesapeake basin-wide index of biotic integrity, or “Chessie BIBI,” is an index of stream health. It was developed from an integrated database of macroinvertebrate data sets originally collected by federal, state, and county agencies, and volunteers in the Chesapeake watershed (Buchanan et al. 2011). An update and refinement of the Chessie BIBI was completed by ICPRB in May of 2017 and the final report can be downloaded from the [ICPRB website]("https://www.potomacriver.org/focus-areas/aquatic-life/chessie-bibi-stream-health-indicator/"). The effort was guided by a Technical Advisory Group (TAG) consisting of the data providers and area experts. The CBP will be adding the refined Chessie BIBI scores and ratings to their [CEDR database]("http://data.chesapeakebay.net/LivingResources").

The Chessie BIBI refinement explored three taxonomic resolutions (i.e., order, family, and genus) and three spatial resolutions (i.e., basin-wide, region, and bioregion). Order-level indices provided promising results but variability in these indices was often greater than the family and genus resolutions. Genus-level indices generally provided comparable classification efficiency to the family-level indices, and therefore, following the concept of parsimony, the family-level indices were favored. Using season as an additional blocking factor for generating indices may result in a significant improvement in genus-level performance, but was beyond the scope of the current refinement.

The basin-wide spatial resolution uses one suite of macroinvertebrate metrics to evaluate all streams across the basin.  Morphological differences between inland and coastal streams, and the resulting natural differences in stream populations, strongly biased the results and the basin-wide index was not recommended. Regional indices and bioregion indices provided relatively unbiased results that are sensitive to geographic differences. 

The two regional indices (Coastal, Inland) were favored for CBP reporting purposes because of parsimony. By aggregating large swaths of the basin, the regional indices could be derived from larger sample sizes and more reference sites.  Within each region, one suite of metrics was used to develop the index, so index scores could be directly compared across large distances (e.g., Southern Virginia vs. Southern New York). The bioregion indices reflect macroinvertebrate community composition across smaller, more homogeneous areas. The bioregion indices are each evaluated with the metrics most sensitive to their natural characteristics. The number and quality of reference conditions also varies by bioregion. Thus, even though each bioregion index is developed in the same manner, scores of one index should not be directly compared to scores of another index because they reflect each indices accuracy and biases. These differences are overcome by using the same approach for rating each index score. The 50th, 25th, and 10th percentiles of each index version’s scores in reference environmental conditions were used to define Excellent, Good, Fair, and Poor macroinvertebrate status. A fifth rating, Very Poor, was defined by half the value of the 10th percentile. Ratings of the various index versions are considered directly comparable.

The twelve bioregions may be slightly more specific and sensitive to geographic differences but summarizing and comparing results across the basin is easier with the regional indices. @SmithRefinementBasinWideIndex2017 recommend the regional family-level indices for CBP reporting purposes; the family-level bioregion indices represent a valid alternative or could be used in combination with the family-level regional indices to evaluate stream condition locally within the Chesapeake Bay basin.

One of the goals in the [2014 Chesapeake Bay Agreement](https://www.chesapeakebay.net/what/what_guides_us/watershed_agreement) is to “Improve health and function of ten percent of stream miles above the 2008 baseline for the watershed.” The Chesapeake Bay Program (CBP) selected the Chessie BIBI as its biological indicator of stream health. It will use the index to evaluate and report progress improving stream communities across the Chesapeake watershed. This report describes the process used to define a 2008 baseline for the Chessie BIBI.  