---
title: "Untitled"
author: "Zachary M. Smith"
date: "December 27, 2017"
output: html_document
---

```{r echo=FALSE}
knitr::opts_chunk$set(eval=evaluate, cache=cache.me)
```



### Agency Sampling Area


```{r, message=FALSE, fig.width = 8, fig.height = 10}
ggplot() +
  geom_polygon(data = fortify(state.clip),
               aes(long, lat, group = group),
               color = "black", fill = "#999999") +
  geom_point(data = bibi.sub[bibi.sub$period == "2000_2008", ],
             aes(longitude, latitude), color = "#0072B2") +
  coord_equal() +
  facet_wrap(~agency_code) +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) 
```




### State Program Sampling Frequency


```{r}
bibi.state <- bibi.sub %>% 
  mutate(state_program = case_when(
    str_detect(agency_code, "dnrec") ~ "DNREC",
    str_detect(agency_code, "mddnr") ~ "MDDNR",
    str_detect(agency_code, "nydec") ~ "NYDEC",
    str_detect(agency_code, "padep") ~ "PADEP",
    str_detect(agency_code, "vadeq") ~ "VADEQ",
    str_detect(agency_code, "wvdep") ~ "WVDEP",
    str_detect(agency_code, "ddoe") ~ "DDOE",
    TRUE ~ "remove"
  ),
  state_program = factor(state_program,
                         levels = c("DDOE", "DNREC", "NYDEC", 
                                    "PADEP", "WVDEP", "VADEQ", "MDDNR")),
  year = year(date)) %>% 
  filter(!state_program == "remove",
         year >= 2000,
         year <= 2011,
         latitude > 0) %>% 
  complete(state_program, year)
```


```{r, warning=FALSE, fig.width = 8, fig.height = 20}
ggplot() +
  geom_polygon(data = suppressMessages(fortify(state.clip)),
               aes(long, lat, group = group),
               color = "black", fill = "#999999") +
  geom_point(data = bibi.state,
             aes(longitude, latitude, color = state_program), size = 1.5) +
  scale_color_manual(values = c(
    "DNREC" = "#E69F00",
    "MDDNR" = "#56B4E9",
    "NYDEC" = "#009E73",
    "PADEP" = "#F0E442",
    "VADEQ" = "#0072B2",
    "WVDEP" = "#D55E00",
    "DDOE" = "#CC79A7")) +
  coord_equal() +
  theme_bw() +
  theme(
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
    #labs(title = state.program) +
  facet_wrap(~year, ncol = 2)

```





```{r}
huc12.poly <- gbuf(huc12.poly)
# DISSOLVE BASED ON "REGION" COLUMN USING rgeos::gUnionCascaded 
basin.poly2 <- gUnionCascaded(basin.poly, id = basin.poly@data$OBJECTID)
```





```{r}

huc12.poly2 <- gBuffer(head(huc12.poly, 20), byid = TRUE, width = 0)
test2 <- subset(huc12.poly, HUC12 %in% head(unique(huc12.poly@data$HUC12)))
plot(test2)

huc12.poly@data$ID <- huc12.poly@data$HUC12
test <- fortify(huc12.poly)
# DISSOLVE BASED ON "REGION" COLUMN USING rgeos::gUnionCascaded 
huc12.poly2 <- rgeos::gUnionCascaded(head(huc12.poly), id = head(huc12.poly@data$HUC12))


# CREATE A DATAFRAME OF VALUES RETAINED FROM "REGION" COLUMN
sdf <- data.frame(ID = row.names(huc12.poly))

# ASSIGN "REGION" VALUES TO rownames SO DATA MATCHES slots CORRECTLY
row.names(sdf) <- row.names(huc12.poly)

# CREATE A SpatialPolygonsDataFrame OBJECT WITH A data slot HOLDING REGION IDS.  
huc12.poly2 <-  SpatialPolygonsDataFrame(huc12.poly, huc12.poly@data$HUC12) 

#huc12.poly <- subset(huc12.poly, !ID %in% c("020600010000", "020801010000", "020700111001"))
```

```{r}

bibi.pts <- bibi.sub
coordinates(bibi.pts) <- ~ longitude + latitude
proj4string(bibi.pts) <- CRS("+init=epsg:4269")
CRS.new <- CRS("+proj=utm +zone=18 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0")
bibi.pts <- spTransform(bibi.pts, CRS.new)
bibi.pts <- data.frame(bibi.pts)

```

```{r}
bibi.0408 <- bibi.pts %>% 
  filter(period == "2004_2008")

bibi.0008 <- bibi.pts %>% 
  filter(period == "2000_2008")
```


```{r}

bibi.0408.gis <- bibi.0408
coordinates(bibi.0408.gis) <- ~ longitude + latitude
proj4string(bibi.0408.gis) <- CRS("+proj=utm +zone=18 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0")

```

```{r}
huc12.0408 <- huc12.poly@data$Samples[if_else(huc12.poly@data$HUC12 %in% unique(bibi.0408$huc_12), "Present", "Absent")]
```

```{r}
huc12.0408 <- fortify(huc12.poly) %>% 
  mutate(Samples = if_else(id %in% unique(bibi.0408$huc_12), "Present", "Absent"))

huc12.0008 <- fortify(huc12.poly) %>% 
  mutate(Samples = if_else(id %in% unique(bibi.0008$huc_12), "Present", "Absent"))

huc12.fort <- fortify(huc12.poly) %>% 
  mutate(`2004_2008` = if_else(id %in% unique(bibi.0408$huc_12), "Present", "Absent"),
         `2000_2008` = if_else(id %in% unique(bibi.0008$huc_12), "Present", "Absent")) %>% 
  gather(period, Samples, `2004_2008`:`2000_2008`)
```


```{r, fig.width = 8, fig.height = 10}
ggplot() +
  geom_polygon(data = huc12.0408, aes(long, lat, group = group, fill = Samples),
               color = "black") +
  scale_fill_manual(values = c("Absent" = "#999999", "Present" = "#0072B2")) +
  coord_equal() +
  theme_bw() +
  theme(
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()
  ) 

```

```{r}
huc12.0408 %>% 
  mutate(total = n()) %>% 
  group_by(Samples, total) %>% 
  summarize(Percentage = n() / unique(total) * 100,
            Percentage = round(Percentage, 1)) %>% 
  select(-total) %>% 
  knitr::kable()
```

```{r, fig.width = 8, fig.height = 10}
ggplot() +
  geom_polygon(data = huc12.0008, aes(long, lat, group = group, fill = Samples),
               color = "black") +
  scale_fill_manual(values = c("Absent" = "#999999", "Present" = "#0072B2")) +
  coord_equal() +
  theme_bw() +
  theme(
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()
  ) 

```

```{r}
huc12.0008 %>% 
  mutate(total = n()) %>% 
  group_by(Samples, total) %>% 
  summarize(Percentage = n() / unique(total) * 100,
            Percentage = round(Percentage, 1)) %>% 
  select(-total) %>% 
  knitr::kable()
```

```{r}
huc12.clip <- gIntersection(huc12.poly, county.spdf, byid = TRUE) %>% 
  SpatialPolygonsDataFrame(data.frame(id = names(.), 
                                      row.names = names(.)))
baltimore <- subset(huc12.clip, grepl("maryland_baltimore", id))

bibi.baltimore <- bibi.pts %>% 
  filter(agency_code == "bc_dep_bcwmp")
coordinates(bibi.baltimore) <- ~ longitude + latitude
proj4string(bibi.baltimore) <- CRS("+proj=utm +zone=18 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0")

bibi.baltimore<- data.frame(bibi.baltimore)
baltimore <- suppressMessages( fortify(baltimore))
ggplot() +
  geom_polygon(data = baltimore, aes(long, lat, group = group),
               color = "black", fill = "#999999") +
  #annotation_map(fortify(clip2), fill = "#999999", colour = "black") +
  geom_point(data = bibi.baltimore, aes(longitude, latitude)) +
  coord_equal() +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()
  ) 


```


